### ISSUE TITLE
Multiple issues, incomptabile with ComfyUI@b249862

### ISSUE THREAD

**Issue by zopieux** [phineas-pta/comfy-trt-test#11]
Comfy version: (latest master): https://github.com/comfyanonymous/ComfyUI/commit/b249862080d4c046bd7f2680898c2f348c792a12

Issues I encounter:

* https://github.com/phineas-pta/comfy-trt-test/blob/45b5d2a37c36ed7c028dc14aeabf1540da237017/convert_unet.py#L155 is missing new argument `controlnet`, therefore one should add `controlnet=False` to the arguments.
* `TrtUnetWrapper_Patch` does not match upstream class `ModelPatcher`, for instance today it fails because it expects [method `get_model_object`](https://github.com/comfyanonymous/ComfyUI/blob/b249862080d4c046bd7f2680898c2f348c792a12/comfy/model_patcher.py#L177)

Thanks for sharing these nodes!

**Comment by phineas-pta** [comment]
thank you for the notice, i'll update when possible

**Comment by phineas-pta** [comment]
comfyui got an official tensorrt node: https://github.com/comfyanonymous/ComfyUI_TensorRT

there's no need to compete so i'll stop updating mine

thank you for your time

**Comment by zopieux** [comment]
Thanks for the link.
